### ISSUE TITLE
使用模拟账号买入，有个弹窗确认，自动点取消了

### ISSUE THREAD

**Issue by manyhelp** [wukan1986/thsauto#1]
confirm, prompt = t.buy(100, 7.1, code='600000')
print(confirm, prompt)

{'标题': '委托买入确认', '账户': 'A123456', '名称': '浦发银行', '代码': '600000', '数量': 100, '价格': 7.1} {}

**Comment by wukan1986** [comment]
```
# 初次使用请在`debug=True`模式下多测试几次
# 再次测试在模拟炒股下再开启`debug=False`
# 然后再在其它账号下`debug=True`模式下测试
# 最后是其它账号下`debug=False`下交易
t = THS(debug=True, skip_popup=False)
t.connect(addr="emulator-5554")
```


为了防止操作失误，默认参数为`debug=True`，需要设置为`debug=False`

**Comment by manyhelp** [comment]
`
[D 231017 17:54:24 __init__:661] [pid:2120] [emulator-5554] kill process(ps): uiautomator
2023-10-17 17:54:24.426 | INFO     | thsauto.utils:__exit__:16 - code executed in 2.4565136 seconds
Traceback (most recent call last):
  File "D:\devsoft\Miniconda3\lib\site-packages\uiautomator2\__init__.py", line 486, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "D:\devsoft\Miniconda3\lib\site-packages\uiautomator2\__init__.py", line 519, in _jsonrpc_call
    raise GatewayError(
uiautomator2.exceptions.GatewayError: (<Response [502]>, 'gateway error, time used 0.0s')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\quant\thsauto\examples\demo.py", line 12, in <module>
    t.connect(addr="emulator-5554")
  File "K:\quant\thsauto\thsauto\ths.py", line 57, in connect
    return self.d.info
  File "D:\devsoft\Miniconda3\lib\site-packages\uiautomator2\__init__.py", line 448, in info
    return self.jsonrpc.deviceInfo(http_timeout=10)
  File "D:\devsoft\Miniconda3\lib\site-packages\uiautomator2\__init__.py", line 479, in __call__
    return self.server._jsonrpc_retry_call(self.method, params,
  File "D:\devsoft\Miniconda3\lib\site-packages\uiautomator2\__init__.py", line 488, in _jsonrpc_retry_call
    self.reset_uiautomator(str(e))  # uiautomator可能出问题了，强制重启一下
  File "D:\devsoft\Miniconda3\lib\site-packages\uiautomator2\__init__.py", line 640, in reset_uiautomator
    ok = self._force_reset_uiautomator_v2(
  File "D:\devsoft\Miniconda3\lib\site-packages\uiautomator2\__init__.py", line 667, in _force_reset_uiautomator_v2
    if self._is_apk_required():
  File "D:\devsoft\Miniconda3\lib\site-packages\uiautomator2\__init__.py", line 711, in _is_apk_required
    if self._package_version("com.github.uiautomator.test") is None:
  File "D:\devsoft\Miniconda3\lib\site-packages\uiautomator2\__init__.py", line 735, in _package_version
    return packaging.version.parse(m.group('name') if m else "")
  File "D:\devsoft\Miniconda3\lib\site-packages\packaging\version.py", line 52, in parse
    return Version(version)
  File "D:\devsoft\Miniconda3\lib\site-packages\packaging\version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''
`
出了个新问题，麻烦大佬看下，adb已经连接好了。

**Comment by wukan1986** [comment]
https://github.com/openatx/uiautomator2/issues/906

> 或者降低uiautomator2的版本,或者降低packaging版本
> pip install packaging==21.3

你可以试试，我目前还没有遇到此问题

**Comment by manyhelp** [comment]
安装的是这个版本。不知道什么原因，重启电脑解决。多谢大佬。
